# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech Thoughts & Learnings
email: 
description: > # this means to ignore newlines until "baseurl:"
  A blog highlighting what I am reading, building, learning and thinking about. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fanwar.github.io" # the base hostname & protocol for your site
twitter_username: fanwar1981
github_username:  fanwar

# Build settings
markdown: kramdown
